##
## EPITECH PROJECT, 2022
## arcade
## File description:
## common
##

CXX	=	g++

CXXFLAGS	=	-fno-gnu-unique -W -Wall -Werror -std=c++20 -g

SRC	=

OBJ	=	$(SRC:.cpp=.o)


all: $(SRC)

clean:
	rm -rf $(SRC)

fclean: clean

re: fclean all

